const fs = require('fs');
const path = 'D:\\Escritorio\\Antigravity\\Palma Real\\palma-real-app\\src\\pages\\Cobranzas.jsx';

let content = fs.readFileSync(path, 'utf8');

// Find the start of the units map inside <tbody>
const startMarker = '{loading ? (';
const startIdx = content.indexOf(startMarker);
if (startIdx === -1) { console.error('START NOT FOUND'); process.exit(1); }

// Find the end of the units map (the closing }) before </tbody>
const endMarker = '</tbody>';
const endIdx = content.indexOf(endMarker);
if (endIdx === -1) { console.error('END NOT FOUND'); process.exit(1); }

console.log('Replacing table body content between', startIdx, 'and', endIdx);

const newBody = [
    '                            {loading ? (',
    '                                <tr><td colSpan="8" className="px-6 py-20 text-center animate-pulse font-mono text-sm text-slate-400">Procesando matriz de datos...</td></tr>',
    '                            ) : units.filter(u => u.number.toLowerCase().includes(searchTerm.toLowerCase()) || (u.owner_name || "").toLowerCase().includes(searchTerm.toLowerCase())).map(u => {',
    '                                const metrics = getUnitMetrics(u.id);',
    '                                const isSolvente = metrics.remaining <= 0.01;',
    '                                return (',
    '                                    <tr key={u.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/30 transition-colors">',
    '                                        <td className="px-6 py-3 border-r border-slate-200 dark:border-slate-800">',
    '                                            <div className="flex flex-col">',
    '                                                <span className="font-black text-slate-900 dark:text-white text-sm uppercase">{u.number}</span>',
    '                                                <span className="text-[10px] font-bold text-slate-500 uppercase tracking-tighter truncate max-w-[150px]">{u.owners?.full_name || "Sin Propietario"}</span>',
    '                                            </div>',
    '                                        </td>',
    '                                        <td className="px-6 py-3 border-r border-slate-200 dark:border-slate-800 text-right bg-slate-50/20">',
    '                                            {metrics.saldoFavor > 0 ? (',
    '                                                <div className="flex flex-col items-end gap-0.5">',
    '                                                    <span className="text-sm font-black font-mono text-emerald-600 dark:text-emerald-400">',
    '                                                        + {formatNumber(metrics.saldoFavor)} $',
    '                                                    </span>',
    '                                                    <span className="text-[9px] font-black uppercase tracking-widest text-emerald-500 bg-emerald-50 dark:bg-emerald-900/20 px-1.5 py-0.5 rounded-sm">',
    '                                                        Saldo a Favor',
    '                                                    </span>',
    '                                                </div>',
    '                                            ) : (',
    '                                                <span className={`text-sm font-bold font-mono ${metrics.predeuda > 0 ? "text-red-400" : "text-slate-400"}`}>',
    '                                                    {formatNumber(metrics.predeuda || 0)} $',
    '                                                </span>',
    '                                            )}',
    '                                        </td>',
    '                                        <td className="px-6 py-3 border-r border-slate-200 dark:border-slate-800 text-right">',
    '                                            <div className="flex flex-col">',
    '                                                <span className="text-sm font-black font-mono text-slate-600 dark:text-slate-300">{formatNumber(metrics.mesCursoBase || 0)} $</span>',
    '                                            </div>',
    '                                        </td>',
    '                                        <td className="px-6 py-3 border-r border-slate-200 dark:border-slate-800 text-right bg-slate-50/50 dark:bg-slate-800/20">',
    '                                            <div className="flex flex-col items-end gap-0.5">',
    '                                                <span className={`text-sm font-black font-mono ${(metrics.deudaTotal || 0) > 0 ? "text-red-500" : "text-emerald-500"}`}>',
    '                                                    {formatNumber(metrics.deudaTotal || 0)} $',
    '                                                </span>',
    '                                                {metrics.saldoFavor > 0 && (',
    '                                                    <span className="text-[9px] font-mono text-emerald-500">',
    '                                                        {formatNumber(metrics.mesCursoBase)} − {formatNumber(metrics.saldoFavor)} $',
    '                                                    </span>',
    '                                                )}',
    '                                                {metrics.predeuda > 0 && (',
    '                                                    <span className="text-[9px] font-mono text-red-400">',
    '                                                        {formatNumber(metrics.predeuda)} + {formatNumber(metrics.mesCursoBase)} $',
    '                                                    </span>',
    '                                                )}',
    '                                            </div>',
    '                                        </td>',
    '                                        <td className="px-6 py-3 border-r border-slate-200 dark:border-slate-800 text-right font-mono text-sm font-bold">',
    '                                            <span className={(metrics.paidBs || 0) > 0 ? "text-emerald-600 dark:text-emerald-400" : "text-slate-400"}>',
    '                                                {formatNumber(metrics.paidBs || 0)} Bs',
    '                                            </span>',
    '                                        </td>',
    '                                        <td className="px-6 py-3 border-r border-slate-200 dark:border-slate-800 text-right font-mono text-sm font-bold">',
    '                                            <span className={(metrics.paidUsd || 0) > 0 ? "text-emerald-600 dark:text-emerald-400" : "text-slate-400"}>',
    '                                                {formatNumber(metrics.paidUsd || 0)} $',
    '                                            </span>',
    '                                        </td>',
    '                                        <td className="px-6 py-3 border-r border-slate-200 dark:border-slate-800 text-right">',
    '                                            {(() => {',
    '                                                const rem = metrics.remaining || 0;',
    '                                                if (rem < -0.01) {',
    '                                                    return (',
    '                                                        <div className="flex flex-col items-end gap-0.5">',
    '                                                            <span className="text-sm font-black font-mono text-emerald-500">',
    '                                                                + {formatNumber(Math.abs(rem))} $',
    '                                                            </span>',
    '                                                            <span className="text-[9px] font-black uppercase tracking-widest text-emerald-500 bg-emerald-50 dark:bg-emerald-900/20 px-1.5 py-0.5 rounded-sm">Saldo a Favor</span>',
    '                                                        </div>',
    '                                                    );',
    '                                                } else if (rem > 0.01) {',
    '                                                    return <span className="text-sm font-black font-mono text-amber-500 dark:text-amber-400">{formatNumber(rem)} $</span>;',
    '                                                } else {',
    '                                                    return <span className="text-sm font-black font-mono text-emerald-500">0.00 $</span>;',
    '                                                }',
    '                                            })()}',
    '                                        </td>',
    '                                        <td className="px-6 py-3 text-center">',
    '                                            {!isSolvente && (',
    '                                                <button',
    '                                                    onClick={async () => {',
    '                                                        setLoading(true);',
    '                                                        try {',
    '                                                            const { data: fullUnit, error: uError } = await supabase',
    '                                                                .from("units")',
    '                                                                .select("*, owners(full_name, doc_id, email, phone)")',
    '                                                                .eq("id", u.id)',
    '                                                                .single();',
    '                                                            if (uError) throw uError;',
    '',
    '                                                            const { data: periods, error: pError } = await supabase',
    '                                                                .from("condo_periods")',
    '                                                                .select("id, period_name, reserve_fund, period_expenses(amount)")',
    '                                                                .eq("tower_id", selectedTower)',
    '                                                                .eq("status", "PUBLICADO")',
    '                                                                .order("created_at", { ascending: false });',
    '                                                            if (pError) throw pError;',
    '',
    '                                                            const { data: allocations, error: aError } = await supabase',
    '                                                                .from("unit_payment_allocations")',
    '                                                                .select("amount_allocated, period_id, unit_payments!inner(unit_id)")',
    '                                                                .eq("unit_payments.unit_id", u.id);',
    '                                                            if (aError) throw aError;',
    '',
    '                                                            const pm = {};',
    '                                                            (allocations || []).forEach(a => {',
    '                                                                pm[a.period_id] = (pm[a.period_id] || 0) + parseFloat(a.amount_allocated);',
    '                                                            });',
    '',
    '                                                            const charges = [];',
    '                                                            const iDebt = parseFloat(fullUnit.initial_debt || 0);',
    '                                                            let credit = iDebt < 0 ? Math.abs(iDebt) : 0;',
    '',
    '                                                            if (iDebt > 0) {',
    '                                                                charges.push({',
    '                                                                    id: "INITIAL_DEBT",',
    '                                                                    period_name: "SALDO ANTERIOR",',
    '                                                                    aliquot: iDebt,',
    '                                                                    paid_amount: 0,',
    '                                                                    status: "DEUDA",',
    '                                                                    type: "HISTORY",',
    '                                                                    sortKey: 0',
    '                                                                });',
    '                                                            }',
    '',
    '                                                            const sortedP = [...(periods || [])].sort((a, b) => {',
    '                                                                const partsA = a.period_name.split(" ");',
    '                                                                const partsB = b.period_name.split(" ");',
    '                                                                const yA = parseInt(partsA[1]) || 0;',
    '                                                                const yB = parseInt(partsB[1]) || 0;',
    '                                                                const mA = monthMap[partsA[0].toUpperCase()] || 0;',
    '                                                                const mB = monthMap[partsB[0].toUpperCase()] || 0;',
    '                                                                if (yA !== yB) return yB - yA;',
    '                                                                return mB - mA;',
    '                                                            });',
    '',
    '                                                            sortedP.forEach(p => {',
    '                                                                const parts = p.period_name.split(" ");',
    '                                                                const y = parseInt(parts[1]) || 0;',
    '                                                                const m = monthMap[parts[0].toUpperCase()] || 0;',
    '                                                                const sk = y * 100 + m;',
    '                                                                const te = p.period_expenses.reduce((s, exp) => s + parseFloat(exp.amount), 0);',
    '                                                                const al = parseFloat(((te + parseFloat(p.reserve_fund || 0)) / 16).toFixed(2));',
    '                                                                const pd = pm[p.id] || 0;',
    '                                                                charges.push({',
    '                                                                    id: p.id,',
    '                                                                    period_name: p.period_name,',
    '                                                                    aliquot: al,',
    '                                                                    paid_amount: pd,',
    '                                                                    status: pd >= al - 0.05 ? "PAGADO" : "DEUDA",',
    '                                                                    type: "CONDO",',
    '                                                                    sortKey: sk',
    '                                                                });',
    '                                                            });',
    '',
    '                                                            charges.sort((a, b) => a.sortKey - b.sortKey);',
    '',
    '                                                            const pending = [];',
    '                                                            charges.forEach(c => {',
    '                                                                if (c.status === "DEUDA") {',
    '                                                                    let amt = parseFloat((c.aliquot - c.paid_amount).toFixed(2));',
    '                                                                    if (credit > 0 && amt > 0) {',
    '                                                                        const app = Math.min(credit, amt);',
    '                                                                        credit -= app;',
    '                                                                        amt = parseFloat((amt - app).toFixed(2));',
    '                                                                    }',
    '                                                                    if (amt > 0.05) {',
    '                                                                        pending.push({ ...c, amount: amt });',
    '                                                                    }',
    '                                                                }',
    '                                                            });',
    '',
    '                                                            setSelectedUnit(fullUnit);',
    '                                                            setSelectedUnitPendingPeriods(pending);',
    '                                                            setShowPaymentModal(true);',
    '',
    '                                                        } catch (err) {',
    '                                                            console.error("Error modal:", err);',
    '                                                        } finally {',
    '                                                            setLoading(false);',
    '                                                        }',
    '                                                    }}',
    '                                                    className="px-3 py-1.5 bg-slate-900 text-white dark:bg-white dark:text-slate-900 text-[10px] font-black uppercase tracking-widest flex items-center gap-1 hover:invert transition-all"',
    '                                                    title="Asentar Pago"',
    '                                                >',
    '                                                    <span className="material-icons text-[12px]">payments</span>',
    '                                                    PAGAR',
    '                                                </button>',
    '                                            )}',
    '                                        </td>',
    '                                    </tr>',
    '                                );',
    '                            })}'
].join('\n');

const newContent = content.substring(0, startIdx) + newBody + '\n' + content.substring(endIdx);

// Also fix the footer metrics
const footerOld = /sum \+ Math.max\(0, m.predeuda \+ m.mesCurso - m.paidUsd\)/g;
const footerNew = 'sum + Math.max(0, m.remaining)';
let finalContent = newContent.replace(footerOld, footerNew);

// Temporary fix for the status in Footer too (uses .status which might be wrong if renamed)
finalContent = finalContent.replace(/metrics.status === 'Solvente'/g, 'metrics.remaining <= 0.01');

fs.writeFileSync(path, finalContent, 'utf8');
console.log('Successfully repaired Cobranzas.jsx row logic and footer.');
